const INDIGO = '#6366f1';
const CYAN = '#06b6d4';
const EMERALD = '#10b981';
const AMBER = '#f59e0b';
const ROSE = '#f43f5e';

const state = {
  page: 'login',
  authMode: 'login',
  role: 'candidate',
  section: 'overview',
  email: '',
  password: '',
  name: '',
  org: '',
  search: '',
  temp: 0.7,
  authError: '',
  authMessage: '',
  resetToken: '',
  resetPasswordConfirmation: '',
  showPassword: false,
  user: null,
  token: null,
  currentInterview: null,
  currentQuestionIndex: 0,
  currentTranscript: '',
  sessionMessage: '',
  recordingsData: null,
  activeVideoModal: null,
  interviewStream: null,
  voiceCapture: null,
  interviewerAudio: null,
  mediaRecorder: null,
  recordedChunks: [],
  audioMonitor: null,
  autoStopFallback: null,
  liveTranscript: '',
  liveParts: null,
  silenceTimer: null,
  configModal: null,
  configRound: 'Technical Interview',
  configJobRole: '',
  configDifficulty: 'medium',
  configMode: 'time',
  configNumQuestions: 5,
  configTimeDuration: 15,
  configFocus: [],
  configQuestionStyle: 'Mixed',
  configInterviewerStyle: 'Professional',
  configResume: null,
  resumeStatus: 'idle',
  resumeError: '',
  deviceTested: false,
  configError: '',
  analyticsData: null,
  analyticsTrendMetric: 'all',
  analyticsSkillTab: 'technical',
  activeReportModal: null,
  historyData: null,
  reportsData: null,
  historySearch: '',
  historyTypeFilter: 'all',
  historyRatingFilter: 'all',
  historyDateFilter: 'all',
  historySort: 'newest',
  historyPage: 1,
  historyPerPage: 5,
  assessmentTargetRole: '',
  assessmentSelectedTopics: ['Data Structures', 'Algorithms', 'Python', 'SQL'],
  assessmentDifficulty: 'medium',
  assessmentNumQuestions: 10,
  assessmentTimeLimit: 10,
  assessmentCustomTime: 10,
  assessmentResult: null,
  assessmentHistoryData: null,
  recruiterSummaryData: null,
  recruiterCandidatesData: null,
  recruiterCandidatesSearch: '',
  recruiterCandidatesStatusFilter: 'all',
  recruiterLiveSessionsData: null,
  recruiterSessionsStatusFilter: 'all',
  recruiterSessionsData: null,
  recruiterTemplatesData: null,
  showCreateTemplateModal: false,
  recruiterCompareSelectedIds: [],
  recruiterCompareData: null,
  recruiterCandidateModal: null,
  candidateJobsTab: 'explore',
  candidateJobsSearch: '',
  candidateJobsDomain: 'all',
  candidateJobsLocation: 'all',
  candidateJobsType: 'all',
  candidateJobsData: null,
  candidateMyApplicationsData: null,
  selectedApplyJob: null,
  applyCoverNote: '',
  isApplyingJob: false,
  recruiterJobsData: null,
  recruiterSelectedJobId: null,
  recruiterJobApplicantsData: null,
  recruiterJobModalOpen: false,
  editingJobId: null,
  recruiterJobForm: {
    title: '',
    company_name: '',
    domain: 'Software Engineering',
    location_type: 'Remote',
    job_type: 'Full-time',
    experience_level: 'Mid Level',
    salary_range: '',
    skills: '',
    description: '',
    requirements: ''
  },
  assessmentResume: null,
  assessmentResumeStatus: 'idle',
  assessmentResumeError: '',
  assessmentError: '',
  currentAssessment: null,
  currentAssessmentQuestions: [],
  assessmentQuestionIndex: 0,
  assessmentAnswers: {},
  assessmentTimerInterval: null,
  assessmentTimeRemaining: 600,
  assessmentStream: null,
  assessmentFaceStatus: 'Detected',
  assessmentEyeContact: 88,
  assessmentExpression: 'Neutral',
  assessmentIntegrity: { face_detected_pct: 95, eye_contact_pct: 88, look_away_events: 1, multiple_faces_events: 0, expression_distribution: { Neutral: '85%', Focused: '15%' } },
  assessmentResult: null,
  submitConfirmModal: false,
  aiVoiceEnabled: true,
  isFullscreen: false,
  telemetryWpm: 140,
  telemetryFillerWords: 0,
  telemetryEyeContact: 92,
  telemetryEmotion: 'Composed',
  answerStartTime: null,
  notificationsData: null,
  unreadNotifCount: 0,
  isNotifDropdownOpen: false,
  notifActiveTab: 'all',
  notifLoading: false,
  vision: null,
  attention: null,
  attentionTerminated: false,
  resumeAnalyzer: {
    stage: 'landing',
    fileName: '',
    level: '',
    role: '',
    roleCustom: '',
    result: null,
    error: '',
  },
  adminOverviewData: null,
  adminUsersData: null,
  adminInterviewsData: null,
  adminAIPerfData: null,
  adminSystemHealthData: null,
  adminActivityLogData: null,
  adminUsersFilterRole: 'all',
  adminUsersSearch: '',
  adminInterviewsFilterStatus: 'all',
  adminInterviewsSearch: '',
  adminShowAddUserModal: false,
};

let charts = {};
