import { useEffect, useRef, useState } from 'react'
import { BriefcaseBusiness, CalendarDays, CheckCircle2, Clock3, FileText, MapPin, Mic, Play, Send, TrendingUp, Upload, X } from 'lucide-react'
import Sidebar from '../components/Sidebar'
import Topbar from '../components/Topbar'
import { useAuth } from '../auth/AuthContext'
import { candidateApi } from '../auth/api'

function InterviewModal({ job, onClose, onSaved }) {
  const [interviewAt, setInterviewAt] = useState('')
  const [error, setError] = useState('')
  const [saving, setSaving] = useState(false)
  const submit = async (event) => { event.preventDefault(); setSaving(true); setError(''); try { onSaved(await candidateApi.requestInterview(job.application_id, new Date(interviewAt).toISOString())); onClose() } catch (err) { setError(err.message) } finally { setSaving(false) } }
  return <div style={{ position: 'fixed', inset: 0, zIndex: 2000, display: 'grid', placeItems: 'center', padding: 20, background: 'rgba(0,0,0,.65)', backdropFilter: 'blur(6px)' }}><form onSubmit={submit} className="glass-strong" style={{ width: '100%', maxWidth: 480, borderRadius: 20, padding: 28 }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 18 }}><div><h2 style={{ color: '#f0f0ff', fontFamily: 'Outfit' }}>Request interview</h2><p style={{ color: '#a0a0c0', fontSize: '.82rem', marginTop: 4 }}>{job.title} · {job.company}</p></div><button type="button" onClick={onClose} style={{ background: 'transparent', color: '#a0a0c0' }}><X /></button></div><label className="form-group"><span className="form-label">Preferred date and time</span><input className="form-input" type="datetime-local" value={interviewAt} onChange={(event) => setInterviewAt(event.target.value)} required /></label>{error && <p style={{ color: '#f87171', fontSize: '.82rem', marginTop: 12 }}>{error}</p>}<button className="btn btn-primary" style={{ width: '100%', justifyContent: 'center', marginTop: 18 }} disabled={saving}>{saving ? 'Sending...' : 'Send request'}</button></form></div>
}

export default function CandidateDashboard() {
  const { user } = useAuth()
  const displayName = user?.name || 'Candidate'
  const initials = displayName.split(' ').map((part) => part[0]).join('').slice(0, 2).toUpperCase()
  const [jobs, setJobs] = useState([])
  const [error, setError] = useState('')
  const [busyJob, setBusyJob] = useState(null)
  const [requestJob, setRequestJob] = useState(null)
  const [resumeName, setResumeName] = useState('')
  const [activeTool, setActiveTool] = useState('')
  const resumeInput = useRef(null)
  useEffect(() => { candidateApi.jobs().then(setJobs).catch((err) => setError(err.message)) }, [])
  const apply = async (job) => { setBusyJob(job.id); try { const application = await candidateApi.apply(job.id); setJobs((items) => items.map((item) => item.id === job.id ? { ...item, application_id: application.id, application_status: application.status } : item)) } catch (err) { setError(err.message) } finally { setBusyJob(null) } }
  const requestInterview = (updated) => setJobs((items) => items.map((item) => item.application_id === updated.id ? { ...item, application_status: updated.status } : item))
  const applied = jobs.filter((job) => job.application_id)
  const scheduled = jobs.filter((job) => job.application_status === 'INTERVIEW_SCHEDULED').length
  const handleCandidateNavigation = (label) => {
    const targets = { Dashboard: 'candidate-dashboard-top', 'Start Interview': 'candidate-tools', 'Upload Resume': 'candidate-tools', 'My Reports': 'candidate-tools', History: 'candidate-jobs' }
    if (label === 'Start Interview') setActiveTool('Mock interview ready: Tell me about yourself.')
    if (label === 'My Reports') setActiveTool('Performance analysis is ready for your next completed mock interview.')
    if (label === 'Upload Resume') resumeInput.current?.click()
    document.getElementById(targets[label])?.scrollIntoView({ behavior: 'smooth', block: 'start' })
  }
  return <div className="dashboard-layout" id="candidate-dashboard-top"><Sidebar role="candidate" onNavigate={handleCandidateNavigation} /><div className="dashboard-main"><Topbar title="Candidate Dashboard" subtitle="Develop your skills and find your next opportunity" userName={displayName} userInitials={initials} roleBadge="Candidate" /><main className="dashboard-content"><div style={{ marginBottom: 28 }}><h2 style={{ color: '#f0f0ff', fontFamily: 'Outfit' }}>Your career workspace</h2><p style={{ color: '#a0a0c0', marginTop: 5, fontSize: '.85rem' }}>Practice, prepare your resume, and apply to live opportunities.</p></div>{error && <p role="alert" style={{ color: '#f87171', marginBottom: 16 }}>{error}</p>}<div className="grid-cols-3" style={{ marginBottom: 32 }}><div className="stat-card"><div className="stat-card-icon" style={{ background: '#6366f118' }}><BriefcaseBusiness color="#6366f1" /></div><div className="stat-card-value" style={{ color: '#818cf8' }}>{jobs.length}</div><div className="stat-card-label">Open jobs</div></div><div className="stat-card"><div className="stat-card-icon" style={{ background: '#06b6d418' }}><Send color="#06b6d4" /></div><div className="stat-card-value" style={{ color: '#67e8f9' }}>{applied.length}</div><div className="stat-card-label">Applications</div></div><div className="stat-card"><div className="stat-card-icon" style={{ background: '#22c55e18' }}><CalendarDays color="#22c55e" /></div><div className="stat-card-value" style={{ color: '#4ade80' }}>{scheduled}</div><div className="stat-card-label">Interviews scheduled</div></div></div>
        <section className="card" id="candidate-tools" style={{ marginBottom: 32 }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18, flexWrap: 'wrap', gap: 12 }}><div><h3 style={{ color: '#f0f0ff', fontFamily: 'Outfit' }}>Career preparation</h3><p style={{ color: '#606080', fontSize: '.78rem', marginTop: 3 }}>Tools from your original candidate dashboard.</p></div>{activeTool && <span className="badge badge-success">{activeTool}</span>}</div><div className="grid-cols-3" style={{ gap: 16 }}><button onClick={() => resumeInput.current?.click()} style={{ textAlign: 'left', padding: 18, borderRadius: 14, background: 'rgba(99,102,241,.09)', border: '1px solid rgba(99,102,241,.22)', color: 'inherit' }}><Upload size={20} color="#818cf8" /><h4 style={{ color: '#f0f0ff', marginTop: 12 }}>Upload resume</h4><p style={{ color: '#a0a0c0', fontSize: '.78rem', marginTop: 5 }}>{resumeName ? `Selected: ${resumeName}` : 'Choose a PDF or DOCX file for review.'}</p></button><input ref={resumeInput} type="file" accept=".pdf,.doc,.docx" style={{ display: 'none' }} onChange={(event) => { const file = event.target.files?.[0]; if (file) { setResumeName(file.name); setActiveTool('Resume selected') } }} /><button onClick={() => setActiveTool('Mock interview ready: Tell me about yourself.')} style={{ textAlign: 'left', padding: 18, borderRadius: 14, background: 'rgba(6,182,212,.09)', border: '1px solid rgba(6,182,212,.22)', color: 'inherit' }}><Mic size={20} color="#67e8f9" /><h4 style={{ color: '#f0f0ff', marginTop: 12 }}>Mock interview</h4><p style={{ color: '#a0a0c0', fontSize: '.78rem', marginTop: 5 }}>Practice common interview questions.</p><span style={{ color: '#67e8f9', fontSize: '.78rem', display: 'inline-flex', gap: 5, marginTop: 10 }}><Play size={13} /> Start practice</span></button><button onClick={() => setActiveTool('Performance analysis is ready for your next completed mock interview.')} style={{ textAlign: 'left', padding: 18, borderRadius: 14, background: 'rgba(34,197,94,.09)', border: '1px solid rgba(34,197,94,.22)', color: 'inherit' }}><TrendingUp size={20} color="#4ade80" /><h4 style={{ color: '#f0f0ff', marginTop: 12 }}>Performance analysis</h4><p style={{ color: '#a0a0c0', fontSize: '.78rem', marginTop: 5 }}>Review interview feedback and growth.</p><span style={{ color: '#4ade80', fontSize: '.78rem', display: 'inline-flex', gap: 5, marginTop: 10 }}><FileText size={13} /> View insights</span></button></div></section>
        <section className="card" id="candidate-jobs"><h3 style={{ color: '#f0f0ff', fontFamily: 'Outfit', marginBottom: 4 }}>Available jobs</h3><p style={{ color: '#606080', fontSize: '.78rem', marginBottom: 18 }}>Apply to an open job, then request a preferred interview time.</p>{jobs.length === 0 ? <div style={{ padding: '35px 10px', color: '#a0a0c0', textAlign: 'center' }}>No open jobs have been posted yet.</div> : <div style={{ display: 'grid', gap: 14 }}>{jobs.map((job) => <article key={job.id} style={{ padding: 18, border: '1px solid rgba(255,255,255,.08)', borderRadius: 14, background: 'rgba(255,255,255,.025)' }}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' }}><div><h4 style={{ color: '#f0f0ff', fontSize: '1rem' }}>{job.title}</h4><p style={{ color: '#818cf8', fontSize: '.84rem', marginTop: 3 }}>{job.company}</p><p style={{ color: '#a0a0c0', fontSize: '.78rem', marginTop: 8, display: 'flex', alignItems: 'center', gap: 5 }}><MapPin size={13} />{job.location} · {job.employment_type}</p></div><div>{!job.application_id ? <button className="btn btn-primary" disabled={busyJob === job.id} onClick={() => apply(job)}>{busyJob === job.id ? 'Applying...' : 'Apply now'}</button> : job.application_status === 'INTERVIEW_SCHEDULED' ? <span className="badge badge-success"><CheckCircle2 size={12} /> Interview scheduled</span> : job.application_status === 'INTERVIEW_REQUESTED' ? <span className="badge badge-warning"><Clock3 size={12} /> Request sent</span> : <button className="btn btn-outline" onClick={() => setRequestJob(job)}><CalendarDays size={15} /> Request interview</button>}</div></div><p style={{ color: '#a0a0c0', fontSize: '.82rem', lineHeight: 1.6, marginTop: 13 }}>{job.description}</p></article>)}</div>}</section></main></div>{requestJob && <InterviewModal job={requestJob} onClose={() => setRequestJob(null)} onSaved={requestInterview} />}</div>
}
