import { useEffect, useRef, useState } from 'react'
import { BrainCircuit, CheckCircle2, Mic, Pause, Play, Send, Square, Volume2, X } from 'lucide-react'
import { FaceDetector, FilesetResolver } from '@mediapipe/tasks-vision'
import { candidateApi } from '../auth/api'

export default function InterviewGenerator({ onClose, onFinished }) {
  const [details, setDetails] = useState({ role_title: 'Software Developer', domain: 'Technical', difficulty: 'Medium', question_count: 5 })
  const [session, setSession] = useState(null); const [answer, setAnswer] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [recordingStatus, setRecordingStatus] = useState(''); const [listening, setListening] = useState(false); const [proctorReady, setProctorReady] = useState(false); const [warning, setWarning] = useState(''); const [cameraStream, setCameraStream] = useState(null)
  const recognition = useRef(null)
  const mediaStream = useRef(null)
  const recorder = useRef(null)
  const recordingChunks = useRef([])
  const generate = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const created = await candidateApi.generateInterview(details); setSession(await candidateApi.startInterview(created.id)); setProctorReady(false) } catch (err) { setError(err.message) } finally { setBusy(false) } }
  const handleSessionAction = async (action) => {
    if (!session) return
    setBusy(true); setError('')
    try {
      const updated = await ({ start: () => candidateApi.startInterview(session.id), pause: () => candidateApi.pauseInterview(session.id), resume: () => candidateApi.resumeInterview(session.id), end: () => candidateApi.endInterview(session.id) }[action]())
      setSession(updated)
      if (action === 'pause' && recorder.current?.state === 'recording') recorder.current.pause()
      if (action === 'resume' && recorder.current?.state === 'paused') recorder.current.resume()
      if (action === 'end') { await finishRecording(updated.id); stopProctoring() }
    } catch (err) {
      setError(err.message)
    } finally {
      setBusy(false)
    }
  }
  const submitAnswer = async (event) => { event.preventDefault(); setBusy(true); setError(''); try { const updated = await candidateApi.saveInterviewAnswer(session.id, answer); setSession(updated); setAnswer(''); if (updated.status === 'COMPLETED') { await finishRecording(updated.id); stopProctoring(); onFinished?.() } } catch (err) { setError(err.message) } finally { setBusy(false) } }
  const question = session?.questions?.[session.current_question]; const completed = session?.status === 'COMPLETED'; const ended = session?.status === 'ENDED'; const voiceEnabled = session && ['Technical', 'Behavioral'].includes(session.domain)
  const readQuestion = () => { if ('speechSynthesis' in window && question?.text) { window.speechSynthesis.cancel(); window.speechSynthesis.speak(new SpeechSynthesisUtterance(question.text)) } else setError('Question reading is not supported by this browser.') }
  const startListening = () => { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { setError('Voice answers are not supported by this browser. Use Google Chrome or type your answer.'); return } setError(''); const listener = new SpeechRecognition(); recognition.current = listener; listener.continuous = true; listener.interimResults = true; listener.lang = 'en-US'; listener.onstart = () => setListening(true); listener.onresult = (event) => { let finalText = ''; let interim = ''; for (let index = event.resultIndex; index < event.results.length; index += 1) { const transcript = event.results[index][0].transcript; if (event.results[index].isFinal) finalText += `${transcript} `; else interim += transcript } if (finalText) setAnswer((previous) => `${previous} ${finalText}`.trim()); setError(interim ? `Listening: ${interim}` : '') }; listener.onerror = () => { setListening(false); setError('Voice recognition stopped. Allow microphone access, then try again.') }; listener.onend = () => setListening(false); listener.start() }
  const stopListening = () => recognition.current?.stop()
  const startRecording = (stream) => { if (!window.MediaRecorder) { setError('This browser cannot record the interview. Use a current version of Chrome or Edge.'); return } try { const type = ['video/webm;codecs=vp9,opus', 'video/webm'].find((value) => MediaRecorder.isTypeSupported(value)); const activeRecorder = new MediaRecorder(stream, type ? { mimeType: type } : undefined); recordingChunks.current = []; activeRecorder.ondataavailable = (event) => { if (event.data.size) recordingChunks.current.push(event.data) }; activeRecorder.start(1000); recorder.current = activeRecorder; setRecordingStatus('Recording in progress') } catch { setError('Interview recording could not start. Check camera and microphone permissions.') } }
  const finishRecording = async (interviewId) => { const activeRecorder = recorder.current; if (!activeRecorder || activeRecorder.state === 'inactive') { setRecordingStatus('No recording was created'); return } ; setRecordingStatus('Saving recording...'); const blob = await new Promise((resolve) => { activeRecorder.addEventListener('stop', () => resolve(new Blob(recordingChunks.current, { type: activeRecorder.mimeType || 'video/webm' })), { once: true }); activeRecorder.stop() }); recorder.current = null; if (!blob.size) { setRecordingStatus('Recording was empty and was not saved'); return }; const extension = blob.type.includes('mp4') ? 'mp4' : 'webm'; try { const saved = await candidateApi.uploadInterviewRecording(interviewId, new File([blob], `interview-recording.${extension}`, { type: blob.type || 'video/webm' })); setSession(saved); setRecordingStatus('Recording saved securely') } catch (err) { setRecordingStatus(`Recording upload failed: ${err.message}`); throw err } }
  const stopProctoring = () => { mediaStream.current?.getTracks().forEach((track) => track.stop()); mediaStream.current = null; setCameraStream(null); if (document.fullscreenElement) document.exitFullscreen?.() }
  const closeInterview = () => { stopProctoring(); onClose() }
  const enableProctoring = async () => { setError(''); try { const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); mediaStream.current = stream; await document.documentElement.requestFullscreen(); startRecording(stream); setCameraStream(stream); setProctorReady(true) } catch (err) { mediaStream.current?.getTracks().forEach((track) => track.stop()); mediaStream.current = null; setCameraStream(null); setError('Camera, microphone, and fullscreen permission are required to start the interview.') } }
  useEffect(() => { if (!proctorReady) return undefined; const flag = (message) => setWarning(message); const visibility = () => { if (document.hidden) flag('Warning: tab change detected. Return to the interview and remain focused.') }; const fullscreen = () => { if (!document.fullscreenElement) flag('Warning: fullscreen mode was exited. Return to fullscreen to continue.') }; document.addEventListener('visibilitychange', visibility); document.addEventListener('fullscreenchange', fullscreen); window.addEventListener('blur', () => flag('Warning: you moved away from the interview window.')); return () => { document.removeEventListener('visibilitychange', visibility); document.removeEventListener('fullscreenchange', fullscreen); stopProctoring() } }, [proctorReady])
  useEffect(() => { if (voiceEnabled && proctorReady) readQuestion(); return () => { window.speechSynthesis?.cancel(); recognition.current?.stop() } }, [session?.id, session?.current_question, proctorReady])
  return <div style={overlay}><div className="glass-strong" style={card}><div style={header}><div><h2 style={title}><BrainCircuit size={23} style={{ verticalAlign: 'text-bottom', marginRight: 8, color: '#818cf8' }} />AI interview practice</h2><p style={muted}>{voiceEnabled ? 'Voice interview mode: listen, answer aloud, and review the transcript.' : 'Questions and performance feedback are generated for your role.'}</p></div><button type="button" onClick={closeInterview} style={close}><X /></button></div>{warning && <ProctorWarning message={warning} onDismiss={() => setWarning('')} onRestore={() => document.documentElement.requestFullscreen?.()} />}{!session ? <Configuration details={details} setDetails={setDetails} generate={generate} busy={busy} error={error} /> : completed ? <Report feedback={session.feedback} count={session.questions.length} onClose={closeInterview} recordingStatus={recordingStatus} /> : ended ? <EndedSession session={session} onClose={closeInterview} recordingStatus={recordingStatus} /> : !proctorReady ? <ProctorGate start={enableProctoring} error={error} /> : <Question session={session} question={question} answer={answer} setAnswer={setAnswer} submit={submitAnswer} busy={busy} error={error} voiceEnabled={voiceEnabled} listening={listening} readQuestion={readQuestion} startListening={startListening} stopListening={stopListening} onPause={() => handleSessionAction('pause')} onResume={() => handleSessionAction('resume')} onEnd={() => handleSessionAction('end')} />}</div>{proctorReady && <CameraPreview stream={cameraStream} onAlert={setWarning} />}</div>
}

function Configuration({ details, setDetails, generate, busy, error }) { return <form onSubmit={generate} style={{ display: 'grid', gap: 16 }}><label className="form-group"><span className="form-label">Target role</span><input className="form-input" list="roles" value={details.role_title} onChange={(event) => setDetails({ ...details, role_title: event.target.value })} required /><datalist id="roles"><option value="Software Developer" /><option value="Python Developer" /><option value="Data Analyst" /><option value="HR Executive" /></datalist></label><div className="grid-cols-3" style={{ gap: 12 }}><Choice label="Domain" value={details.domain} values={['Technical', 'Behavioral', 'Aptitude']} onChange={(domain) => setDetails({ ...details, domain })} /><Choice label="Difficulty" value={details.difficulty} values={['Easy', 'Medium', 'Hard']} onChange={(difficulty) => setDetails({ ...details, difficulty })} /><Choice label="Questions" value={details.question_count} values={[3, 5, 7, 10]} onChange={(question_count) => setDetails({ ...details, question_count: Number(question_count) })} /></div>{error && <p style={errorStyle}>{error}</p>}<button className="btn btn-primary" disabled={busy} style={full}>{busy ? 'Generating...' : 'Generate interview questions'}</button></form> }
function Choice({ label, value, values, onChange }) { return <label className="form-group"><span className="form-label">{label}</span><select className="form-input" value={value} onChange={(event) => onChange(event.target.value)}>{values.map((item) => <option key={item}>{item}</option>)}</select></label> }
function Question({ session, question, answer, setAnswer, submit, busy, error, voiceEnabled, listening, readQuestion, startListening, stopListening, onPause, onResume, onEnd }) {
  const statusLabel = session?.status === 'PAUSED' ? 'Paused' : session?.status === 'IN_PROGRESS' ? 'In progress' : 'Ready'
  const paused = session.status === 'PAUSED'
  return <form onSubmit={submit}><div style={meta}><span>{session.role_title} · {session.domain} · {session.difficulty}</span><span>Question {session.current_question + 1} of {session.questions.length}</span></div><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12, gap: 10, flexWrap: 'wrap' }}><span style={{ ...muted, color: '#c7d2fe', fontWeight: 700 }}>{statusLabel}</span><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}><button type="button" className="btn btn-outline" onClick={session.status === 'PAUSED' ? onResume : onPause} disabled={busy}><span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}>{session.status === 'PAUSED' ? <Play size={14} /> : <Pause size={14} />}{session.status === 'PAUSED' ? 'Resume' : 'Pause'}</span></button><button type="button" className="btn btn-outline" onClick={onEnd} disabled={busy}><span style={{ display: 'inline-flex', alignItems: 'center', gap: 6 }}><Square size={14} /> End</span></button></div></div><div style={questionBox}><p style={{ color: '#f0f0ff', lineHeight: 1.6 }}>{question?.text}</p></div>{voiceEnabled && <div style={{ display: 'flex', gap: 10, marginTop: 14, flexWrap: 'wrap' }}><button type="button" className="btn btn-outline" onClick={readQuestion}><Volume2 size={16} /> Read question</button><button type="button" className={listening ? 'btn btn-primary' : 'btn btn-outline'} onClick={listening ? stopListening : startListening}><Mic size={16} /> {listening ? 'Stop listening' : 'Answer by voice'}</button></div>}<label className="form-group" style={{ marginTop: 16 }}><span className="form-label">{voiceEnabled ? 'Answer transcript (editable)' : 'Your answer'}</span><textarea className="form-input" rows="6" value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder={voiceEnabled ? 'Click “Answer by voice” or type your answer...' : 'Type your answer here...'} required /></label>{error && <p style={errorStyle}>{error}</p>}<button className="btn btn-primary" disabled={busy || listening} style={full}><Send size={16} />{busy ? 'Generating your report...' : session.current_question + 1 === session.questions.length ? 'Finish and view results' : 'Save answer and continue'}</button></form> }
function ProctorGate({ start, error }) { return <div style={{ textAlign: 'center', padding: '16px 0 8px' }}><h3 style={title}>Ready to begin?</h3><p style={{ ...muted, maxWidth: 480, margin: '10px auto', lineHeight: 1.6 }}>To protect interview integrity, SmartHire needs access to your camera and microphone and will open the interview in fullscreen mode.</p><div style={proctorNote}><strong style={{ color: '#e8e8fa' }}>Recording and privacy notice</strong><p style={{ ...muted, marginTop: 5, lineHeight: 1.5 }}>By starting, you consent to recording your camera and microphone for this interview. The recording is uploaded only when the session ends and is available only to you and platform administrators. Leaving fullscreen, changing tabs, or moving away from the window shows a warning.</p></div>{error && <p style={errorStyle}>{error}</p>}<button className="btn btn-primary" style={full} onClick={start}><Mic size={16} /> Consent and start recorded interview</button></div> }
function EndedSession({ session, onClose, recordingStatus }) { return <div style={{ padding: '10px 0 8px' }}><div style={{ textAlign: 'center', marginBottom: 20 }}><CheckCircle2 size={40} color="#4ade80" /><h3 style={{ ...title, marginTop: 10 }}>Interview ended</h3><p style={{ ...muted, marginTop: 6 }}>This session was ended on {session.ended_at ? new Date(session.ended_at).toLocaleString() : 'today'}.</p></div><div style={reportBox}><strong style={{ color: '#f0f0ff' }}>Session status</strong><p style={{ ...muted, marginTop: 6, lineHeight: 1.55 }}>Status: {session.status}. Started: {session.started_at ? new Date(session.started_at).toLocaleString() : 'Not recorded'}. Ended: {session.ended_at ? new Date(session.ended_at).toLocaleString() : 'Not recorded'}.</p><p style={{ ...muted, marginTop: 8, color: session.has_recording ? '#86efac' : '#fca5a5' }}>Recording: {recordingStatus || (session.has_recording ? 'Saved securely' : 'Not saved')}</p></div><button className="btn btn-primary" onClick={onClose} style={full}>Close</button></div> }
function ProctorWarning({ message, onDismiss, onRestore }) { return <div style={warningBox}><strong>Interview integrity warning</strong><p style={{ marginTop: 4, fontSize: '.82rem', lineHeight: 1.45 }}>{message}</p><div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 9 }}><button type="button" onClick={onRestore} style={warningButton}>Return to fullscreen</button><button type="button" onClick={onDismiss} style={warningButton}>I understand</button></div></div> }
function CameraPreview({ stream, onAlert }) {
  const video = useRef(null)
  useEffect(() => { if (video.current && stream) video.current.srcObject = stream }, [stream])
  useEffect(() => {
    if (!stream) return undefined
    let detector; let timer; let running = true
    const setupDetector = async () => {
      try {
        const vision = await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@latest/wasm')
        detector = await FaceDetector.createFromOptions(vision, {
          baseOptions: { modelAssetPath: 'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/1/blaze_face_short_range.tflite' },
          runningMode: 'VIDEO', minDetectionConfidence: 0.55,
        })
        timer = window.setInterval(checkCamera, 3000)
      } catch { onAlert('Camera monitoring could not start. Your interview can continue, but camera face warnings are unavailable.') }
    }
    const checkCamera = async () => {
      if (!running || !video.current || video.current.readyState < 2) return
      try {
        const faces = detector.detectForVideo(video.current, performance.now()).detections || []
        if (faces.length === 0) onAlert('Warning: no face is visible. Please remain visible to the camera.')
        else if (faces.length > 1) onAlert('Warning: more than one face is visible. Only the candidate should be present.')
        else {
          const box = faces[0].boundingBox
          const center = (box.x + box.width / 2) / video.current.videoWidth
          if (center < 0.25 || center > 0.75 || box.width / video.current.videoWidth < 0.15) onAlert('Warning: please face the camera and remain clearly visible.')
        }
      } catch { /* Monitoring is non-blocking if a frame cannot be analysed. */ }
    }
    setupDetector()
    return () => { running = false; window.clearInterval(timer); detector?.close() }
  }, [stream, onAlert])
  return <div style={cameraPreview}><video ref={video} autoPlay muted playsInline style={{ width: '100%', height: '100%', objectFit: 'cover', transform: 'scaleX(-1)' }} /><span style={cameraLabel}>● Recording</span></div>
}
function Report({ feedback, count, onClose, recordingStatus }) { const scores = feedback?.category_scores || {}; return <div style={{ padding: '4px 0 8px' }}><div style={{ textAlign: 'center', marginBottom: 24 }}><CheckCircle2 size={42} color="#4ade80" /><h3 style={{ ...title, marginTop: 10 }}>Your performance report</h3><p style={{ ...muted, marginTop: 6 }}>{count} answers assessed by AI.</p>{feedback?.overall_score > 0 && <div style={{ color: '#67e8f9', fontSize: '2.3rem', fontWeight: 800, marginTop: 14 }}>{feedback.overall_score}<span style={{ fontSize: '1rem', color: '#a0a0c0' }}>/100</span></div>}</div><ReportSection title="Score breakdown">{Object.entries(scores).map(([name, score]) => <div key={name} style={scoreRow}><span style={{ textTransform: 'capitalize', color: '#dadaeb' }}>{name.replace('_', ' ')}</span><strong style={{ color: '#818cf8' }}>{score}/100</strong></div>)}</ReportSection><ReportSection title="Strengths"><Points values={feedback?.strengths} /></ReportSection><ReportSection title="Improve next"><Points values={feedback?.improvements} /></ReportSection><div style={reportBox}><strong style={{ color: '#f0f0ff' }}>Summary</strong><p style={{ ...muted, marginTop: 6, lineHeight: 1.55 }}>{feedback?.summary || 'Your answers have been saved.'}</p>{recordingStatus && <p style={{ ...muted, marginTop: 8, color: recordingStatus.includes('saved') ? '#86efac' : '#fca5a5' }}>Recording: {recordingStatus}</p>}</div><button className="btn btn-primary" onClick={onClose} style={full}>Close report</button></div> }
function ReportSection({ title, children }) { return <div style={{ marginTop: 15 }}><h4 style={{ color: '#f0f0ff', fontSize: '.9rem', marginBottom: 8 }}>{title}</h4>{children}</div> }
function Points({ values }) { return values?.length ? <ul style={{ color: '#c4c4dd', fontSize: '.84rem', lineHeight: 1.7, paddingLeft: 19 }}>{values.map((value, index) => <li key={index}>{value}</li>)}</ul> : <p style={muted}>No feedback available.</p> }
const overlay = { position: 'fixed', inset: 0, zIndex: 2000, overflowY: 'auto', display: 'grid', placeItems: 'center', padding: 20, background: 'rgba(0,0,0,.72)', backdropFilter: 'blur(7px)' }; const card = { width: '100%', maxWidth: 650, borderRadius: 20, padding: 28, margin: 'auto' }; const header = { display: 'flex', justifyContent: 'space-between', gap: 16, marginBottom: 20 }; const title = { color: '#f0f0ff', fontFamily: 'Outfit' }; const muted = { color: '#a0a0c0', fontSize: '.82rem' }; const close = { background: 'transparent', color: '#a0a0c0', height: 30 }; const full = { width: '100%', justifyContent: 'center', marginTop: 18 }; const errorStyle = { color: '#f87171', fontSize: '.84rem', marginTop: 10 }; const meta = { display: 'flex', justifyContent: 'space-between', color: '#a0a0c0', fontSize: '.8rem', marginBottom: 12 }; const questionBox = { padding: 18, borderRadius: 14, background: 'rgba(99,102,241,.10)', border: '1px solid rgba(129,140,248,.25)' }; const reportBox = { padding: 14, borderRadius: 12, background: 'rgba(99,102,241,.08)', border: '1px solid rgba(129,140,248,.18)', marginTop: 14 }; const scoreRow = { display: 'flex', justifyContent: 'space-between', padding: '8px 10px', borderBottom: '1px solid rgba(255,255,255,.07)', fontSize: '.84rem' }
const proctorNote = { textAlign: 'left', padding: 14, borderRadius: 12, background: 'rgba(99,102,241,.08)', border: '1px solid rgba(129,140,248,.2)', marginTop: 18 }; const warningBox = { position: 'sticky', top: 0, zIndex: 4, padding: 14, borderRadius: 12, background: 'rgba(127,29,29,.96)', color: '#fee2e2', border: '1px solid rgba(248,113,113,.6)', marginBottom: 14 }; const warningButton = { padding: '6px 11px', borderRadius: 7, background: '#f8717122', color: '#fecaca', border: '1px solid #f8717155' }
const cameraPreview = { position: 'fixed', right: 22, bottom: 22, zIndex: 2100, width: 170, height: 128, overflow: 'hidden', borderRadius: 12, background: '#11111c', border: '2px solid rgba(129,140,248,.8)', boxShadow: '0 12px 28px rgba(0,0,0,.45)' }; const cameraLabel = { position: 'absolute', left: 8, bottom: 7, padding: '3px 7px', borderRadius: 6, background: 'rgba(0,0,0,.7)', color: '#d9f99d', fontSize: '.7rem' }
