requireAuth('admin');
wireLogoutButton('#logoutBtn');
// Construct real sections before shared controls load on DOMContentLoaded.
(() => {
 const {api,esc,say,run}=window.dashboardTools;
 const modules=[['overview','⌂ Overview'],['users','♙ User & recruiter management'],['activity','◉ Interview activity'],['ai-config','✦ AI performance'],['analytics','↗ Platform usage'],['health','♡ System health'],['reports','▤ Reports'],['feedback','✉ Feedback inbox'],['settings','⚙ Settings']];
 document.querySelector('.admin-sidebar nav').innerHTML=modules.map(([id,label])=>`<a href="#${id}">${label}</a>`).join('')+'<a href="notifications.html">♢ Notifications & Reports</a>';
 const main=document.querySelector('main'), header=main.querySelector('header');main.replaceChildren(header);
 for(const [id,title] of modules){const s=document.createElement('section');s.id=id;s.className='section';s.innerHTML=`<h2>${title}</h2><div class="dt-panel" id="admin-${id}">Loading…</div>`;main.append(s);}
 document.querySelector('#admin-settings').outerHTML='<div class="settings-panel dt-panel">Loading preferences…</div>';
 let data;
 const table=(heads,rows)=>'<div class="dt-table"><table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
 function users(){const q=document.querySelector('#adminUserSearch').value.toLowerCase(),role=document.querySelector('#adminRole').value;document.querySelector('#adminUserRows').innerHTML=table(['Name','Email','Role','Status','Action'],data.users.filter(u=>(!role||u.role===role)&&(u.name+' '+u.email).toLowerCase().includes(q)).map(u=>[esc(u.name),esc(u.email),esc(u.role),u.active?'Active':'Disabled',u.role==='admin'?'Protected':`<button data-user="${esc(u.id)}" data-active="${!u.active}">${u.active?'Disable':'Enable'}</button>`]));}
 async function refresh(){data=await api('/dashboard/admin');const candidateCount=data.users.filter(u=>u.role==='candidate').length,recruiterCount=data.users.filter(u=>u.role==='recruiter').length,activeCount=data.users.filter(u=>u.active).length,completedCount=data.interviews.filter(i=>i.status==='completed').length;document.querySelector('#admin-overview').innerHTML=`<div class="dt-section-head"><div><span class="dt-section-kicker">Live command center</span><h3>Platform pulse</h3><p>Current account, interview and scoring activity from PostgreSQL.</p></div><button id="adminRefresh">↻ Refresh data</button></div><div class="dt-grid">${[['♙','Candidates',candidateCount,'Registered talent accounts'],['♜','Recruiters',recruiterCount,'Hiring accounts'],['◉','Interviews',data.interviews.length,completedCount+' completed'],['↗','Average score',data.average==null?'—':data.average+'%',data.average==null?'Awaiting scored interviews':'Across scored interviews']].map(([icon,k,v,detail])=>`<article class="dt-metric"><span class="dt-metric-icon">${icon}</span><span class="dt-score">${v}</span><p><strong>${k}</strong><br>${detail}</p></article>`).join('')}</div><div class="dt-profile-grid"><div class="dt-insight"><span>●</span><div><strong>${activeCount} active accounts</strong><div>${data.users.length-activeCount} currently disabled</div></div></div><div class="dt-insight"><span>✓</span><div><strong>${data.health.database}</strong><div>Database status checked ${new Date(data.generated_at).toLocaleTimeString()}</div></div></div></div>`;
 document.querySelector('#adminRefresh').onclick=()=>run(refresh);
 document.querySelector('#admin-users').innerHTML='<label>Search users<input id="adminUserSearch" type="search" placeholder="Name or email"></label><label>Role<select id="adminRole"><option value="">All roles</option><option>candidate</option><option>recruiter</option><option>admin</option></select></label><div id="adminUserRows"></div>';
 document.querySelector('#adminUserSearch').oninput=users;document.querySelector('#adminRole').onchange=users;users();
 document.querySelector('#adminUserRows').onclick=e=>{const b=e.target.closest('[data-user]');if(!b||!confirm('Change this account status?'))return;run(async()=>{await api('/dashboard/admin/users/'+b.dataset.user,{method:'PATCH',body:JSON.stringify({active:b.dataset.active==='true'})});await refresh();say('Account updated')})};
 document.querySelector('#admin-activity').innerHTML='<div class="dt-inline-filters"><label>Search interview<input id="adminInterviewSearch" type="search" placeholder="Candidate, domain or interview ID"></label><label>Filter status<select id="adminStatus"><option value="">All interviews</option><option>created</option><option>in_progress</option><option>completed</option></select></label></div><div id="adminActivityRows"></div>';
 const activity=()=>{const status=document.querySelector('#adminStatus').value,q=document.querySelector('#adminInterviewSearch').value.trim().toLowerCase();const rows=data.interviews.filter(i=>(!status||i.status===status)&&(!q||(i.candidate+' '+i.domain+' '+i.id).toLowerCase().includes(q)));document.querySelector('#adminActivityRows').innerHTML=table(['Candidate','Domain','Status','Score','Created'],rows.map(i=>[esc(i.candidate),esc(i.domain),esc(i.status),i.score==null?'Not scored':esc(i.score)+'%',esc(new Date(i.created).toLocaleString())]))+(rows.length?'':'<p class="dt-empty">No matching interview evidence.</p>');};document.querySelector('#adminStatus').onchange=activity;document.querySelector('#adminInterviewSearch').oninput=activity;activity();
 const coverage=data.answered_questions?Math.round(data.scored_questions/data.answered_questions*100):0,totalMethods=Math.max(1,...Object.values(data.scoring_methods));document.querySelector('#admin-ai-config').innerHTML=`<div class="dt-section-head"><div><span class="dt-section-kicker">Scoring observability</span><h3>Assessment engine coverage</h3><p>Track whether answered questions received a recorded score and which engine handled them.</p></div><span class="dt-chip">Live operational data</span></div><div class="dt-ai-layout"><div class="dt-ring" style="--value:${coverage}"><strong>${coverage}%</strong><small>coverage</small></div><div><div class="dt-grid"><article class="dt-metric"><span class="dt-score">${data.scored_questions}</span><p>Scored questions</p></article><article class="dt-metric"><span class="dt-score">${data.answered_questions-data.scored_questions}</span><p>Awaiting or missing scores</p></article></div>${Object.entries(data.scoring_methods).map(([k,v])=>`<div class="dt-method"><div class="dt-method-head"><strong>${esc(k)}</strong><span>${v} questions</span></div><span class="dt-bar"><i style="width:${v/totalMethods*100}%"></i></span><p>${Math.round(v/Math.max(1,data.scored_questions)*100)}% of recorded scores</p></div>`).join('')}</div></div><div class="dt-insight"><span>i</span><div><strong>What this metric means</strong><div>Coverage measures completed scoring records. Accuracy requires a labelled evaluation set and is intentionally not guessed here.</div></div></div>`;
 const max=Math.max(1,...Object.values(data.daily));document.querySelector('#admin-analytics').innerHTML='<p>Interview creation by day — latest 30 active days</p>'+Object.entries(data.daily).map(([day,n])=>`<details class="dt-item"><summary>${day} · ${n} interviews<span class="dt-bar"><i style="width:${n/max*100}%"></i></span></summary><p>${n} interviews created on this UTC date.</p></details>`).join('')+(Object.keys(data.daily).length?'':'<p>No interview activity yet.</p>');
 document.querySelector('#admin-health').innerHTML=table(['Check','Result'],Object.entries(data.health).map(([k,v])=>[esc(k.replaceAll('_',' ')),esc(v)]))+`<p>Checked: ${esc(new Date(data.generated_at).toLocaleString())}</p>`;
 document.querySelector('#admin-reports').innerHTML=`<div class="dt-report-hero"><div class="dt-report-copy"><span class="dt-section-kicker">Evidence & exports</span><h3>Platform reporting center</h3><p>Create an operational snapshot with accounts, interview activity, AI scoring coverage and system health. Candidate interview reports remain permission-aware.</p><div class="dt-report-actions"><button id="adminDownload">↓ Platform snapshot</button><a href="notifications.html">Interview report library →</a></div></div><div class="dt-report-preview"><div><span>▤</span><strong>${data.interviews.length} interviews tracked</strong><p>${data.users.length} accounts · ${data.scored_questions} scored answers</p></div></div></div><div class="dt-profile-grid"><div class="dt-profile-stat"><small>Snapshot format</small><strong>JSON · machine readable</strong></div><div class="dt-profile-stat"><small>Generated</small><strong>${esc(new Date(data.generated_at).toLocaleString())}</strong></div></div>`;
 document.querySelector('#adminDownload').onclick=()=>{const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='platform-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Platform snapshot downloaded')};
 const feedbackRows=data.feedback||[];document.querySelector('#admin-feedback').innerHTML=`<div class="dt-section-head"><div><span class="dt-section-kicker">Candidate & recruiter voice</span><h3>Feedback inbox</h3><p>Real submissions received from the public landing page.</p></div><span class="dt-chip">${feedbackRows.length} submission${feedbackRows.length===1?'':'s'}</span></div>`+(feedbackRows.length?table(['Submitted by','Category','Rating','Message','Received'],feedbackRows.map(f=>[`${esc(f.name)}<br><span class="dt-muted">${esc(f.email)}</span>`,esc(f.category),f.rating?esc(f.rating)+'/5':'—',`<span title="${esc(f.message)}">${esc(f.message.length>120?f.message.slice(0,120)+'…':f.message)}</span>`,esc(new Date(f.created_at).toLocaleString())])):'<p class="dt-empty">No feedback has been submitted yet.</p>');
 }
 run(refresh);
})();
