/* Shared account tools. All data requests use the signed-in user's token. */
(() => {
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const pct = v => v == null ? 'Not scored' : Number(v).toFixed(1)+'%';
  let user, inbox={items:[],unread:0};
  async function api(path, options={}) {const r=await authFetch(path, options); const d=await r.json();if(!r.ok)throw Error(typeof d.detail==='string'?d.detail:'Request failed');return d;}
  function say(message){const el=document.createElement('div');el.className='dt-status';el.setAttribute('role','status');el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),6000);}
  function modal(title,html,{icon='✦',subtitle='AI Interview Pro workspace',footer=''}={}){document.querySelector('.dt-dialog')?.close();document.querySelector('.dt-dialog')?.remove();const d=document.createElement('dialog');d.className='dt-dialog';d.innerHTML=`<div class="dt-dialog-shell"><header class="dt-dialog-head"><span class="dt-dialog-icon">${icon}</span><div class="dt-dialog-title"><h2>${esc(title)}</h2><span class="dt-dialog-subtitle">${esc(subtitle)}</span></div><button class="dt-close" aria-label="Close dialog">×</button></header><div class="dt-dialog-body">${html}</div>${footer?`<footer class="dt-dialog-foot">${footer}</footer>`:''}</div>`;document.body.append(d);d.querySelector('.dt-close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target===d)d.close()});d.showModal();return d;}
  async function run(fn){try{await fn()}catch(e){say(e.message)}}
  function installAction(selector,label,fn){const old=document.querySelector(selector);const b=document.createElement('button');b.className='dt-action';b.type='button';b.textContent=label;b.setAttribute('aria-label',label);b.onclick=()=>run(fn);if(old)old.replaceWith(b);else document.querySelector('.header-actions')?.prepend(b);return b;}
  function openInterviewEvidence(row, dialog){
    dialog.close();
    if(user.role==='candidate'){
      window.location.assign(`candidate.html?completed_interview=${encodeURIComponent(row.id)}#analytics`);
      return;
    }
    if(user.role==='recruiter'){
      document.getElementById('sharedInterviews')?.scrollIntoView({behavior:'smooth'});
      if(typeof window.openSharedReport==='function') window.openSharedReport(row.id);
      else say('The shared report viewer is still loading. Please try again.');
      return;
    }
    const searchInput=document.getElementById('adminInterviewSearch');
    if(searchInput){
      searchInput.value=row.id;
      searchInput.dispatchEvent(new Event('input'));
    }
    document.getElementById('activity')?.scrollIntoView({behavior:'smooth'});
  }
  async function search(){
    const d=modal('Search workspace','<div class="dt-search-field"><input id="dtSearch" type="search" placeholder="Search modules, candidates or interviews" aria-label="Search workspace"></div><div class="dt-search-meta"><span id="dtResultCount">Quick links</span><span>Press Esc to close</span></div><div id="dtResults"></div>',{icon:'⌕',subtitle:'Move anywhere without scrolling'});
    const links=[...document.querySelectorAll('aside nav a')].map(a=>({name:a.textContent.trim(),href:a.getAttribute('href')}));
    const data=await api('/dashboard/evidence');
    const render=()=>{
      const q=d.querySelector('input').value.trim().toLowerCase();
      const matchedLinks=links.filter(x=>x.name.toLowerCase().includes(q));
      const matchedRows=data.trend.filter(x=>(x.name+' '+x.domain).toLowerCase().includes(q)).slice(-10).reverse();
      d.querySelector('#dtResultCount').textContent=`${matchedLinks.length+matchedRows.length} result${matchedLinks.length+matchedRows.length===1?'':'s'}`;
      let html='';
      if(matchedLinks.length) html+=`<div class="dt-search-group"><h3>Dashboard modules</h3>${matchedLinks.map(x=>`<a class="dt-result" href="${esc(x.href)}"><span class="dt-result-icon">${x.name.slice(0,2).match(/[\p{Emoji}]/u)?.[0]||'◇'}</span><span><strong>${esc(x.name.replace(/^\S+\s/,''))}</strong><small>Open dashboard section</small></span><span class="dt-result-arrow">→</span></a>`).join('')}</div>`;
      if(matchedRows.length) html+=`<div class="dt-search-group"><h3>Interview evidence</h3>${matchedRows.map(x=>`<button type="button" class="dt-result" data-evidence-id="${esc(x.id)}"><span class="dt-result-icon">◎</span><span><strong>${esc(x.domain)}</strong><small>${esc(x.name)} · ${pct(x.score)} · Open interview report</small></span><span class="dt-result-arrow">→</span></button>`).join('')}</div>`;
      d.querySelector('#dtResults').innerHTML=html||'<div class="dt-empty">No matches. Try a candidate name, interview domain or module.</div>';
    };
    d.querySelector('input').oninput=render;
    d.querySelector('#dtResults').onclick=e=>{
      const evidenceButton=e.target.closest('[data-evidence-id]');
      if(evidenceButton){
        const row=data.trend.find(item=>String(item.id)===evidenceButton.dataset.evidenceId);
        if(row) openInterviewEvidence(row,d);
        return;
      }
      if(e.target.closest('a')) d.close();
    };
    render();
    d.querySelector('input').focus();
  }
  function notificationMarkup(n){const icons={reminder:'◷',session:'▶',performance:'↗'},delivery={disabled:'Email off',pending:'Email queued',sent:'Email sent',failed:'Email failed',not_configured:'Email setup needed'};return `<article class="dt-notification ${n.read?'read':''}" data-kind="${esc(n.kind)}"><span class="dt-notification-icon">${icons[n.kind]||'•'}</span><div><h3>${esc(n.title)}${n.read?'':' <span class="dt-chip">New</span>'}</h3><p>${esc(n.body)}</p><time>${esc(new Date(n.created_at).toLocaleString())}</time><span class="dt-chip">${esc(delivery[n.email_status]||n.email_status)}</span></div>${n.read?'<span class="dt-chip">Read</span>':`<button class="dt-modal-read" data-modal-read="${esc(n.id)}" aria-label="Mark notification as read">✓</button>`}</article>`}
  function showInbox(){const d=modal('Notification center',`<div class="dt-inbox-tools"><span class="dt-inbox-count">${inbox.unread} unread · ${inbox.items.length} total</span><button id="dtRead">Mark all read</button></div><div>${inbox.items.map(notificationMarkup).join('')||'<div class="dt-empty">You are all caught up. New activity will appear here.</div>'}</div>`,{icon:'♢',subtitle:'Reminders, session activity and report updates',footer:'<a href="notifications.html">Open full notification workspace →</a><span class="dt-dialog-subtitle">Refreshes automatically</span>'});d.querySelector('#dtRead').disabled=!inbox.unread;d.querySelector('#dtRead').onclick=()=>run(async()=>{await api('/module9/notifications/read-all',{method:'POST'});await poll(false);showInbox()});d.querySelector('.dt-dialog-body').onclick=e=>{const b=e.target.closest('[data-modal-read]');if(b)run(async()=>{await api('/module9/notifications/'+b.dataset.modalRead+'/read',{method:'POST'});await poll(false);showInbox()})};}
  function profile(){const initials=user.full_name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();const d=modal('Profile & account',`<div class="dt-profile-hero"><span class="dt-avatar">${esc(initials)}</span><div><h3>${esc(user.full_name)}</h3><p>${esc(user.email)}</p><span class="dt-role">${esc(user.role)}</span></div></div><div class="dt-profile-grid"><div class="dt-profile-stat"><small>Account status</small><strong>Active</strong></div><div class="dt-profile-stat"><small>Workspace</small><strong>${esc(user.role)} dashboard</strong></div></div><form id="dtProfile"><label>Display name<input name="full_name" value="${esc(user.full_name)}" required maxlength="150"></label><p class="dt-muted">This name appears in your dashboard and reports.</p><button>Save changes</button></form>`,{icon:'◉',subtitle:'Manage your identity and preferences',footer:'<a href="notifications.html">Notification preferences →</a><span class="dt-dialog-subtitle">Signed in securely</span>'});d.querySelector('form').onsubmit=e=>{e.preventDefault();run(async()=>{const updated=await api('/dashboard/profile',{method:'PATCH',body:JSON.stringify({full_name:new FormData(e.target).get('full_name')})});user={...user,...updated};document.querySelector('#welcomeUser').textContent='Welcome, '+user.full_name+' 👋';d.close();say('Profile updated successfully')})};}
  let bell;
  async function poll(popups=true){inbox=await api('/module9/notifications');bell.innerHTML=`🔔 <span class="dt-badge">${inbox.unread}</span>`;bell.setAttribute('aria-label',`${inbox.unread} unread notifications`);
    if(!popups||document.querySelector('dialog[open]')||document.hidden)return;
    const key='aiip-alerts:'+user.id;let seen=[];try{seen=JSON.parse(localStorage.getItem(key)||'[]')}catch{}
    const alerts=inbox.items.filter(n=>!n.read&&['session','reminder'].includes(n.kind)&&!seen.includes(n.id));
    if(alerts.length){const d=modal('You have a timely update',`<div class="dt-alert-hero"><span class="dt-alert-orbit">◷</span><h3>${alerts.length} session ${alerts.length===1?'alert':'alerts'} waiting</h3><p>Review the schedule or return to an active interview.</p></div><div class="dt-alert-list">${alerts.map(n=>`<article class="dt-alert-card"><strong>${esc(n.title)}</strong><p>${esc(n.body)}</p><time>${esc(new Date(n.created_at).toLocaleString())}</time></article>`).join('')}</div>`,{icon:'✦',subtitle:'Session alerts & reminders',footer:'<button id="dtAcknowledge">Acknowledge</button><a href="notifications.html">Open notification center →</a>'});const acknowledge=()=>{try{localStorage.setItem(key,JSON.stringify([...seen,...alerts.map(n=>n.id)].slice(-500)))}catch{}};d.addEventListener('close',acknowledge,{once:true});d.querySelector('#dtAcknowledge').onclick=()=>d.close();}
  }
  async function preferences(){const panel=document.querySelector('.settings-panel');if(!panel)return;const p=await api('/module9/preferences');panel.className='settings-panel dt-panel';const names={email_enabled:'Email notifications',reminders_enabled:'Interview reminders',session_alerts_enabled:'Session alerts',performance_enabled:'Performance updates'};const ready=!!p.email_configured;panel.innerHTML=Object.entries(names).map(([k,v])=>`<label><input type="checkbox" name="${k}" ${p[k]?'checked':''}><span>${v}</span></label>`).join('')+`<section class="dt-email-card ${ready?'is-ready':'needs-setup'}" aria-label="Email delivery status"><div class="dt-email-icon"><span>✉</span><b>${ready?'✓':'!'}</b></div><div class="dt-email-copy"><small>DELIVERY CHANNEL</small><strong>${ready?'Email delivery is ready':'Email delivery needs setup'}</strong><p>${ready?'Secure notifications can be sent to your registered account address.':'Add valid SMTP credentials to enable external delivery. In-app alerts remain available.'}</p><div class="dt-email-meta"><span>${ready?'● Connected':'● Not connected'}</span><span>${ready?'TLS protected':'In-app only'}</span></div></div></section><div class="dt-pref-actions"><div><strong>Notification controls</strong><small>Changes apply to this ${esc(user.role)} account.</small></div><div class="dt-inline-actions"><button id="dtSavePrefs">Save preferences</button><button id="dtTestEmail" ${ready?'':'disabled'}>Send test email</button><a href="notifications.html">Schedule reminders →</a></div></div>`;panel.querySelector('#dtSavePrefs').onclick=()=>run(async()=>{await api('/module9/preferences',{method:'PUT',body:JSON.stringify(Object.fromEntries(Object.keys(names).map(k=>[k,panel.querySelector(`[name="${k}"]`).checked])))});say('Notification preferences saved')});panel.querySelector('#dtTestEmail').onclick=()=>run(async()=>say((await api('/dashboard/test-email',{method:'POST'})).message));}
  async function evidence(){if(user.role==='admin')return;const host=document.querySelector('#analytics');if(!host)return;const panel=document.createElement('div');panel.className='dt-panel';host.append(panel);panel.innerHTML='<h3>Explore performance</h3><p>Loading interview evidence…</p>';const data=await api('/dashboard/evidence');
    panel.innerHTML=`<div class="dt-section-head"><div><span class="dt-section-kicker">Evidence explorer</span><h3>${user.role==='recruiter'?'Compare candidates & shortlist insights':'Score breakdown & improvement progress'}</h3><p>Filter real completed interview evidence and inspect every score.</p></div><a href="notifications.html">Download reports →</a></div><label>Choose candidate<select id="dtCandidate"><option value="">All available evidence</option>${data.candidates.map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('')}</select></label><div id="dtMetrics"></div><label>Search interview history<input id="dtTrendSearch" placeholder="Search domain or candidate"></label><div id="dtTrend" class="dt-table"></div>`;
    const render=()=>{const id=panel.querySelector('select').value;const c=data.candidates.find(c=>c.id===id);const s=c||data.summary;panel.querySelector('#dtMetrics').innerHTML=`<div class="dt-grid"><div class="dt-metric"><span class="dt-metric-icon">◎</span><span class="dt-score">${pct(s.average)}</span><p>Overall average · ${s.scored} scored interviews</p></div><div class="dt-metric"><span class="dt-metric-icon">★</span><span class="dt-score">${pct(s.best)}</span><p>Best recorded score</p></div>${c?`<div class="dt-metric"><span class="dt-metric-icon">↗</span><span class="dt-score">${c.growth==null?'Need 2 scores':c.growth+' pp'}</span><p>First-to-latest improvement</p></div>`:''}</div>`+Object.entries(s.dimensions).map(([k,v])=>`<details class="dt-item"><summary>${esc(k.replaceAll('_',' '))} · ${pct(v)}<span class="dt-bar"><i style="width:${v??0}%"></i></span></summary><p>Average across answered, scored questions in ${s.completed} completed interviews. ${v==null?'No scored evidence yet.':v<60?'Focus area: practise this dimension and compare your next interview.':'Review question feedback to maintain and improve this skill.'}</p></details>`).join('');const q=panel.querySelector('#dtTrendSearch').value.toLowerCase();const rows=data.trend.filter(t=>(!c||t.candidate_id===c.id)&&(t.name+' '+t.domain).toLowerCase().includes(q));panel.querySelector('#dtTrend').innerHTML='<table><thead><tr><th>Completed</th><th>Candidate / domain</th><th>Score trend</th></tr></thead><tbody>'+rows.slice().reverse().map(t=>`<tr><td>${esc(new Date(t.date).toLocaleDateString())}</td><td><strong>${esc(t.name)}</strong><br><span class="dt-muted">${esc(t.domain)}</span></td><td title="Recorded overall score for this interview"><strong>${pct(t.score)}</strong><span class="dt-bar"><i style="width:${t.score??0}%"></i></span></td></tr>`).join('')+'</tbody></table>'+(rows.length?'':'<p class="dt-empty">No matching completed interviews.</p>');};panel.querySelector('select').onchange=render;panel.querySelector('input').oninput=render;render();
    if(user.role==='recruiter'){const compare=document.createElement('div');compare.className='dt-panel';compare.innerHTML='<h3>Candidate comparison</h3><label>Minimum average score<input id="dtThreshold" type="number" min="0" max="100" value="60"></label><p>Shortlisting hints use shared evidence only; review context before a hiring decision.</p><div class="dt-table" id="dtCompare"></div>';host.append(compare);const draw=()=>{const threshold=Number(compare.querySelector('input').value);compare.querySelector('#dtCompare').innerHTML='<table><tr><th>Rank</th><th>Candidate</th><th>Average</th><th>Technical</th><th>Communication</th><th>Growth</th><th>Insight</th></tr>'+data.candidates.map((c,i)=>`<tr><td>${i+1}</td><td>${esc(c.name)}</td><td>${pct(c.average)}</td><td>${pct(c.dimensions.technical_score)}</td><td>${pct(c.dimensions.communication_score)}</td><td>${c.growth==null?'—':c.growth+' pp'}</td><td>${c.average==null?'Needs scored evidence':c.average>=threshold?'Meets your score threshold':'Below your score threshold'} · ${c.scored} scored</td></tr>`).join('')+'</table>';};compare.querySelector('input').oninput=draw;draw();}
  }
  async function scheduling(){if(user.role!=='recruiter')return;const host=document.querySelector('#interviews');if(!host)return;host.innerHTML='<div class="section-heading"><h2>Interview management</h2><p>Plan reviews and stay ahead of upcoming work.</p></div><div class="dt-panel"><div class="dt-section-head"><div><span class="dt-section-kicker">Schedule</span><h3>Your reminders</h3><p>Personal reminders appear in the dashboard and by email when enabled.</p></div><a href="notifications.html">Manage schedule →</a></div><div id="dtSchedules"></div></div>';const rows=await api('/module9/reminders');host.querySelector('#dtSchedules').innerHTML=rows.length?rows.map(r=>`<article class="dt-notification" data-kind="reminder"><span class="dt-notification-icon">◷</span><div><h3>${esc(r.title)}</h3><p>${esc(new Date(r.scheduled_at).toLocaleString())}</p><span class="dt-chip">${esc(r.status)}</span></div></article>`).join(''):'<div class="dt-empty">No reminders scheduled. Add one from the notification workspace.</div>';}
  function reportHub(){if(user.role!=='recruiter')return;const host=document.querySelector('#reports');if(!host)return;host.innerHTML='<div class="section-heading"><h2>Reports</h2><p>Turn shared interview evidence into clear review material.</p></div><div class="dt-panel dt-report-hero"><div class="dt-report-copy"><span class="dt-section-kicker">Consent scoped evidence</span><h3>Candidate report studio</h3><p>Review question feedback, compare performance, and export only interviews candidates currently share with you.</p><div class="dt-report-actions"><button id="dtSummaryDownload">↓ Download summary CSV</button><a href="notifications.html">Open report library →</a><a href="#candidates">Candidate profiles</a></div></div><div class="dt-report-preview"><div><span>▤</span><strong>Live evidence library</strong><p class="dt-muted">Secure · Exportable · Revocable</p></div></div></div>';host.querySelector('button').onclick=()=>run(async()=>{const r=await authFetch('/module9/reports/summary/download');if(!r.ok)throw Error('Could not download your report. Please retry.');const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download='shared-performance-summary.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Performance summary downloaded')});}
  window.dashboardTools={api,esc,say,run};
  document.addEventListener('DOMContentLoaded',()=>run(async()=>{user=await api('/verify-token');installAction('.search-box','🔍 Search',search);bell=installAction('.header-actions .notification','🔔 Notifications',showInbox);installAction('.header-actions .profile','👤 Profile',profile);reportHub();document.querySelectorAll('main .section').forEach((section,index)=>{section.classList.add('dt-reveal');section.style.setProperty('--dt-delay',Math.min(index*35,210)+'ms')});const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('dt-visible');observer.unobserve(entry.target)}}),{threshold:.08});document.querySelectorAll('.dt-reveal').forEach(section=>observer.observe(section));await Promise.all([preferences(),evidence(),scheduling(),poll()]);setInterval(()=>{if(!document.hidden)run(()=>poll())},30000);window.addEventListener('focus',()=>run(()=>poll()));}));
})();
